apps/planes/urls.py
from django.urls import path, re_path
from . import views

app_name = 'planes'

urlpatterns = [
    path('agregar/', views.agregarPlanes, name="addPlan"),
    path('listar/', views.listarPlanes, name="listPlan"),
    path('listarPlanesPorServicio/', views.listaDePlanesPorServicio, name="listarPlanesPorServicio"),
    path('<int:plan_id>/', views.detallePlan, name="detallePlan"),
    path('editar/<int:plan_id>/', views.editarPlan, name="editarPlan"),

]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('clientes/', include('apps.clientes.urls')),   
    path('planes/', include('apps.planes.urls')),   
    path('servicios/', include('apps.servicios.urls')),   
    path('suscripciones/', include('apps.suscripciones.urls')),   
]

apps/planes/models.py
from django.db import models
from apps.servicios.models import Servicio
# Create your models here.
class Plan(models.Model):
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=240)
    descripcion = models.CharField(max_length=240)
    creado_en = models.DateTimeField(auto_now_add=True)
    editado_en = models.DateTimeField(auto_now=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)  # Adjust max_digits and decimal_places as per your requirement


    def plan_nombre_servicio(self):
        return f"{self.nombre} ({self.servicio.nombre})"

    def fecha_editado_str(self):
        return self.editado_en.strftime("%d-%m-%Y")
    
    def fecha_creacion_str(self):
        return self.creado_en.strftime("%d-%m-%Y")

    def precio_str(self):
        return "$ " + str(self.precio)

apps/planes/views.py
from django.shortcuts import render
from apps.servicios.models import Servicio
from .models import Plan
from django.http import JsonResponse
# Create your views here.


def agregarPlanes(request):
    if request.method == 'POST':

        nombre = request.POST.get('nombre')
        descripcion = request.POST.get('descripcion')
        servicio = request.POST.get('servicio')
        precio = float(request.POST.get('precio'))


        plan_creado = Plan.objects.create(
            nombre=nombre,
            descripcion=descripcion,
            servicio_id=servicio,
            precio=precio
        )




        
        servicios = Servicio.objects.all()

        context = {
            'servicios': servicios,
            'message': f'Se creo el plan  {plan_creado.nombre} con exito',
        }


        return render(request, 'planes/agregarPlanes.html', context )
    else:
        servicios = Servicio.objects.all()

        context = {
            'servicios': servicios
        }

        return render(request, 'planes/agregarPlanes.html', context)

def listarPlanes(request):
    servicios = Servicio.objects.all()

    context = {
        'servicios': servicios
    }


    return render (request, 'planes/listarPlan.html', context)
def listaDePlanesPorServicio(request):
    servicio_id = request.GET.get('servicio_id')

    planes = Plan.objects.filter(servicio_id=servicio_id)

    # Serializar los objetos Plan a un formato JSON
    planes_serializados = [
        {
            'id': plan.id,
            'nombre': plan.nombre,
            'descripcion': plan.descripcion,
            'creado_en': plan.fecha_creacion_str(),  # Convertir a cadena ISO 8601
            'precio': plan.precio_str(),
            'editado_en': plan.fecha_editado_str(),
        } 
        for plan in planes
    ]

    # Devolver la respuesta HTTP con los datos serializados
    return JsonResponse(planes_serializados, safe=False)


def detallePlan(request, plan_id):
    plan = Plan.objects.get(id=plan_id)
    servicio = Servicio.objects.get(id=plan.servicio_id)

    context = {
        'plan': plan,
        'servicio': servicio
    }

    return render(request, 'planes/detallePlan.html', context)


def editarPlan(request, plan_id):
    if request.method == 'POST':

        nombre = request.POST.get('nombre')
        descripcion = request.POST.get('descripcion')
        precio = float(request.POST.get('precio'))

        plan = Plan.objects.get(id=plan_id)
        plan.nombre = nombre
        plan.descripcion = descripcion
        plan.precio = precio
        plan.save()

        context = {
            'message': f'Se edito el plan  {plan.nombre} con exito',
            'plan': plan
        }

        return render(request, 'planes/editarPlan.html', context)
    else:

        plan = Plan.objects.get(id=plan_id)

        context = {
            'plan': plan,
        }

        return render(request, 'planes/editarPlan.html', context)

templates/planes/agregarPlanes.html
{% extends "_base.html" %}

{% block content %}

<div class="flex justify-center">
    <div class="w-full max-w-md">
        <div class="flex justify-center ">

            <h1 class="mb-4 text-2xl font-semibold text-center">AGREGAR PLAN</h1>
        </div>
        {% include 'tools/notificationMessage.html' %}
        <form action="" method="post">
            
            {% csrf_token %}
            <select class="w-full mb-2 px-4 py-2 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500" name="servicio">
                {% for servicio in servicios %}
                <option value="{{servicio.id}}">{{servicio.nombre}}</option>
                {% endfor %}
            </select>
            <input type="text" class="w-full mb-2 px-4 py-2 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500" placeholder="Nombre" name="nombre" required>
            <input type="text" class="w-full mb-2 px-4 py-2 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500" placeholder="Descripcion" name="descripcion" required>
            <input type="number" class="w-full mb-2 px-4 py-2 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500" placeholder="$ 0.00" name="precio" required>
            <button
            class="w-full px-4 py-3 rounded-md bg-indigo-500 text-white font-semibold hover:bg-indigo-600 focus:outline-none focus:bg-indigo-600"
            type="submit">Agregar</button>
        </form>
        {% include 'tools/botonVolver.html '%}

    </div>
</div>

{% endblock content %}

templates/planes/detallePlan.html
{% extends "_base.html" %}

{% block content %}
<div class="bg-gray-100 p-4 rounded-lg shadow-md justify-between max-w-md mx-auto">
    <div class="font-semibold text-lg mb-2">{{ plan.nombre }}</div>
    <div class=" mb-4">
        <div class="w-1/2 pr-2">
            <div><span class="font-semibold">Descripcion:</span> {{ plan.descripcion }}</div>
        </div>



            <div class="font-semibold mb-2 mt-2">Servicio</div>

            <div>
                <div><span class="font-semibold">Nombre:</span> {{ servicio.nombre }}</div>
                <div><span class="font-semibold">Desc:</span> {{ servicio.descripcion }}</div>
            </div>

    </div>
    <div class="font-semibold mb-2">Precio:</div>
    <div class="flex">
        <div class="w-3/4 pr-2">
            <div><span class="font-semibold"></span> {{ plan.precio }}</div>
        </div>
        <div class="w-1/4 pl-2">
            <!-- <div><span class="font-semibold">Número:</span> {{ direccion.numero_calle }}</div> -->
        </div>
    </div>
    <div class="my-4 flex ">
        <!-- {% include 'clientes/enviarWsp.html' with numero=contacto.celular %} -->
        <a href="{% url 'planes:editarPlan' plan.id %}" class="mr-2">
            <button class="flex items-center px-4 py-2 rounded-md bg-indigo-500 text-white font-semibold hover:bg-indigo-600 focus:outline-none focus:bg-indigo-600">
                <svg width="18px" height="18px" viewBox="0 0 24.00 24.00" fill="none" xmlns="http://www.w3.org/2000/svg" class="mr-2">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="m3.99 16.854-1.314 3.504a.75.75 0 0 0 .966.965l3.503-1.314a3 3 0 0 0 1.068-.687L18.36 9.175s-.354-1.061-1.414-2.122c-1.06-1.06-2.122-1.414-2.122-1.414L4.677 15.786a3 3 0 0 0-.687 1.068zm12.249-12.63 1.383-1.383c.248-.248.579-.406.925-.348.487.08 1.232.322 1.934 1.025.703.703.945 1.447 1.025 1.934.058.346-.1.677-.348.925L19.774 7.76s-.353-1.06-1.414-2.12c-1.06-1.062-2.121-1.415-2.121-1.415z" fill="#ffffff"></path>
                    </g>
                </svg>
                Editar
            </button>
        </a>

        <button
        onclick="history.back()"
        class="px-4 py-2 rounded-md bg-indigo-500 text-white font-semibold hover:bg-indigo-600 focus:outline-none focus:bg-indigo-600"
        type="submit">
        Volver
        </button>
        
    </div>
    <div class="my-4">
        <!-- {% include 'clientes/llamarCliente.html' with numero=contacto.celular %} -->


        
    </div>

</div>

{% endblock content %}

templates/planes/editarPlan.html
{% extends "_base.html" %}

{% block content %}

<div class="flex justify-center">
    <div class="w-full max-w-md">
        <div class="flex justify-center ">

            <h1 class="mb-4 text-2xl font-semibold text-center">EDITAR PLAN</h1>
        </div>
        {% include 'tools/notificationMessage.html' %}

        <form action="" method="post">

            {% csrf_token %}

            <input type="text"
                class="w-full mb-2 px-4 py-2 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500"
                placeholder="Nombre" name="nombre" value={{plan.nombre}} required>
            <input type="text"
                class="w-full mb-2 px-4 py-2 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500"
                placeholder="Descripcion" name="descripcion" value={{plan.descripcion}} required>
            <input type="number"
                class="w-full mb-2 px-4 py-2 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500"
                placeholder="$ 0.00" name="precio" value={{plan.precio}} required>
            <button
                class="w-full px-4 py-3 rounded-md bg-indigo-500 text-white font-semibold hover:bg-indigo-600 focus:outline-none focus:bg-indigo-600"
                type="submit">Editar</button>
        </form>
        
        {% include 'tools/botonVolver.html '%}
    </div>
</div>

{% endblock content %}

templates/planes/listarPlan.html
{% extends "_base.html" %}

{% block content %}

<div class="max-w-md mx-auto items-center p-4">
    <!-- <h1>Planes</h1> -->
    <div>
        <select onchange="obtenerPlanesPorServicio()"
            class="w-full mb-2 px-4 py-2 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500"
            name="servicio">
            <option value="" disabled selected hidden>Selecciona un servicio</option>

            {% for servicio in servicios %}
            <option value="{{servicio.id}}">{{servicio.nombre}}</option>
            {% endfor %}
        </select>

    </div>
    <div id="cuerpoTabla" >

        <div class="max-w-md mt-8" style="color:rgb(110,110,110,0.8)"><span class="mx-auto">Ningun servicio seleccionado</span></div>
    </div>
</div>
<script>
    function obtenerPlanesPorServicio() {
        const servicio = document.querySelector('select[name="servicio"]').value;
        fetch(`/planes/listarPlanesPorServicio/?servicio_id=${servicio}`)
            .then(response => response.json())
            .then(data => {
                console.log(data);
                const cuerpoTabla = document.getElementById('cuerpoTabla');
                cuerpoTabla.innerHTML = ''; // Limpiar contenido previo de la tabla

                // Iterar sobre cada plan y agregar una fila a la tabla por cada uno
                if (data.length > 0) {

                    data.forEach(plan => {
                        const url = `/planes/${plan.id}/`;
                        // console.log(plan)
                        const fila = `
                        <style>
                            .flex-container:active {
                                opacity:.5
                            } :hover {
                                bacground-color: rgb(0,0,0,0.05);
                            }
                        </style>
                        <a href="${url}">
                            <div class="flex flex-row justify-between space-y-2 items-center flex-container p-2 rounded">
                                <div class="flex flex-col" style="margin-rigth:2px;">
                                    <span class="font-semibold text-sm">${plan.nombre}</span>
                                    <span class="text-sm">${plan.descripcion}</span>
                                    <div class="flex flex-row">
                                        
                                        <span class="text-sm" style="color:rgb(110,110,110,0.8); margin-right: 1rem;">
                                        ultima edicion: 
                                        {% include 'tools/chip.html' with fecha="${plan.editado_en}" %}
                                        
                                        </span>
                                    </div>
                                    
                                </div>
                                <div class="flex flex-col">
                                    <span class="font-bold" style="color: rgba(99, 101, 241)">${plan.precio}</span>


                                </div>
                            </div>
                        </a>
                            `;
                        cuerpoTabla.innerHTML += fila;
                    });
                }
                else {
                    cuerpoTabla.innerHTML = 'NO TIENE PLANES ADHERIDOS AL SERVICIO'

                }
            })
            .catch(error => {
                console.error('Hubo un problema al obtener los datos:', error);
            });
    }
</script>
{% endblock content %}