apps/servicios/urls.py
from django.urls import path, re_path
from . import views

app_name = 'servicios'

urlpatterns = [
    path('', views.listarServicios, name="listarServicios"),
    path('<str:servicio_id>/', views.borrarServicio, name="borrarServicio"),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('clientes/', include('apps.clientes.urls')),   
    path('planes/', include('apps.planes.urls')),   
    path('servicios/', include('apps.servicios.urls')),   
    path('suscripciones/', include('apps.suscripciones.urls')),   
]

apps/servicios/models.py
from django.db import models

# Create your models here.

class Servicio(models.Model):
    nombre = models.CharField(max_length=240)
    descripcion = models.CharField(max_length=240)

apps/servicios/views.py
from django.shortcuts import render, redirect
from .models import Servicio
# Create your views here.
def listarServicios(request):
    if request.method == 'POST':


        nombre = request.POST.get('nombre')
        descripcion = request.POST.get('descripcion')
        Servicio.objects.create(
            nombre=nombre,
            descripcion=descripcion
        )

        servicios = Servicio.objects.all()

        context = {
            'servicios': servicios
        }
        return render(request, 'servicios/listarServicios.html', context)

    else:
        servicios = Servicio.objects.all()

        context = {
            'servicios': servicios
        }
        return render(request, 'servicios/listarServicios.html', context)


def borrarServicio(request, servicio_id):
    # servicio = Servicio.objects.delete(servicio_id)
    servicio = Servicio.objects.get(pk=servicio_id)
    servicio.delete()

    print(servicio)
    return redirect('servicios:listarServicios')

templates/servicios/listarServicios.html
{% extends "_base.html" %}

{% block content %}

<div class="container mx-auto">
    <form action="" method="post" class="mb-8 max-w-md mx-auto md:max-w-full md:mx-0">
        {% csrf_token %}
        <h4 class="text-2xl font-semibold mb-4">Agregar Servicio</h4>
        <div class="mb-4">
            <input type="text" class="w-full px-4 py-2 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500" placeholder="Nombre" name="nombre" required>
        </div>
        <div class="mb-4">
            <input type="text" class="w-full px-4 py-2 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500" placeholder="Descripción" name="descripcion" required>
        </div>
        <button type="submit" class="w-full px-4 py-2 bg-indigo-500 text-white font-semibold rounded-md hover:bg-indigo-600 focus:outline-none focus:bg-indigo-600">Agregar</button>
    </form>

    <div class="w-full mt-4">
        <h4 class="text-2xl font-semibold mb-4">Lista de Servicio</h4>
        {% include 'tools/notificationMessage.html' %}
        <table class="w-full border-collapse">
            <thead>
                <tr>
                    <th class="py-2 px-4 bg-gray-200 text-gray-700 font-semibold border border-gray-300">ID</th>
                    <th class="py-2 px-4 bg-gray-200 text-gray-700 font-semibold border border-gray-300">Nombre</th>
                    <th class="py-2 px-4 bg-gray-200 text-gray-700 font-semibold border border-gray-300">Descripción</th>
                    <th class="py-2 px-4 bg-gray-200 text-gray-700 font-semibold border border-gray-300">*</th>
                </tr>
            </thead>
            <tbody>
                {% for servicio in servicios %}
                <tr>
                    <td class="py-2 px-4 border border-gray-300">{{ servicio.id }}</td>
                    <td class="py-2 px-4 border border-gray-300">{{ servicio.nombre }}</td>
                    <td class="py-2 px-4 border border-gray-300">{{ servicio.descripcion }}</td>
                    <td class="py-2 px-4 border border-gray-300">
                        <a href="{% url 'servicios:borrarServicio' servicio.id %}" >
                            {% include 'tools/botonEliminar.html' %}
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock content %}