apps/clientes/urls.py
from django.urls import path, re_path
from . import views

app_name = 'clientes'

urlpatterns = [
    path('agregar/', views.agregarCliente, name="addCliente"),
    path('listar/', views.listarCliente, name="listCliente"),
    path('<int:cliente_id>/', views.detalleCliente, name="detailCliente")
]

apps/planes/urls.py
from django.urls import path, re_path
from . import views

app_name = 'planes'

urlpatterns = [
    path('agregar/', views.agregarPlanes, name="addPlan"),
    path('listar/', views.listarPlanes, name="listPlan"),
    path('listarPlanesPorServicio/', views.listaDePlanesPorServicio, name="listarPlanesPorServicio"),
    path('<int:plan_id>/', views.detallePlan, name="detallePlan"),
    path('editar/<int:plan_id>/', views.editarPlan, name="editarPlan"),

]

apps/servicios/urls.py
from django.urls import path, re_path
from . import views

app_name = 'servicios'

urlpatterns = [
    path('', views.listarServicios, name="listarServicios"),
    path('<str:servicio_id>/', views.borrarServicio, name="borrarServicio"),
]

apps/suscripciones/urls.py
from django.urls import path, re_path
from . import views

app_name = 'suscripciones'

urlpatterns = [
    path('agregar/<int:cliente_id>', views.agregarSuscripcion, name="addSuscripcion"),
    path('lista/', views.listarSuscripciones, name="listSuscripcion")

]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('clientes/', include('apps.clientes.urls')),   
    path('planes/', include('apps.planes.urls')),   
    path('servicios/', include('apps.servicios.urls')),   
    path('suscripciones/', include('apps.suscripciones.urls')),   
]

home/views.py
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render
from apps.suscripciones.models import Suscripcion
def sendEmail(request):

    # send_mail(
    #     'Asunto del correo electrónico',
    #     'Cuerpo del correo electrónico.',
    #     'nahuelcaceres@escribanoschaco.com',  # Dirección de correo electrónico del remitente
    #     ['nahuelcaceres@escribanoschaco.com', 'nahuecaceres29@gmail.com'],  # Lista de direcciones de correo electrónico de los destinatarios
    #     fail_silently=False,
    # )
    html = "<html><body>It is now.</body></html>" 
    return HttpResponse(html)
    # 

def index(request):
    sus = Suscripcion.objects.all()
    context = {
        'sus':sus
    }
    
    return render(request, 'home.html', context)

templates/_base.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TVBOX</title>

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}

</head>

<body class="bg-white-50">
    <header class="bg-white">
        <nav class="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
            <div class="flex lg:flex-1">
                <a href="#" class="-m-1.5 p-1.5">
                    <span class="sr-only">Your Company</span>
                    <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
                        alt="">
                </a>
            </div>
            <div class="flex lg:hidden">
                <button type="button" id="openMenuBtn"
                    class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
                        aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                    </svg>
                </button>
            </div>
            <div class="hidden lg:flex lg:gap-x-12">
                <div class="relative">
                    <a href="{% url 'index' %}">

                        <button type="button" id="openInicioBtn"
                            class="flex items-center gap-x-1 text-sm font-semibold leading-6 text-gray-900"
                            aria-expanded="false">
                            Inicio
                        </button>
                    </a>

                    <!--
                'Product' flyout menu, show/hide based on flyout menu state.
      
                Entering: "transition ease-out duration-200"
                  From: "opacity-0 translate-y-1"
                  To: "opacity-100 translate-y-0"
                Leaving: "transition ease-in duration-150"
                  From: "opacity-100 translate-y-0"
                  To: "opacity-0 translate-y-1"
              -->
                </div>

                <a href="{% url 'servicios:listarServicios' %}"
                    class="text-sm font-semibold leading-6 text-grey-900">Servicios</a>



                <!-- <a href="#" class="text-sm font-semibold leading-6 text-grey-900">Clientes</a> -->

                <div class="relative" id="dropdownButtonPlan">
                    <div onclick="toggleDropdown('#dropdownButtonPlan #dropdownPlan')"
                        class="px-5 rounded cursor-pointer font-semibold text-grey-900 flex w-[130px] justify-between text-sm leading-6 items-center">
                        <span>Planes</span>
                        <svg width="10px" height="10px" viewBox="0 0 1024 1024" class="icon" version="1.1"
                            xmlns="http://www.w3.org/2000/svg">
                            <path d="M903.232 256l56.768 50.432L512 768 64 306.432 120.768 256 512 659.072z"
                                fill="#000000" />
                        </svg>

                    </div>
                    <div id="dropdownPlan"
                        class="rounded border-grey-300 absolute top-[50px] bg-white w-[300px] shadow-md hidden">
                        <a href="{% url 'planes:addPlan' %}"
                            class="cursor-pointer hover:bg-grey-300 p-4 block">Agregar</a>
                        <a href="{% url 'planes:listPlan' %}"
                            class="cursor-pointer hover:bg-grey-300 p-4 block">Lista</a>
                    </div>
                </div>
                <div class="relative" id="dropdownButton">
                    <div onclick="toggleDropdown('#dropdownButton #dropdown')"
                        class="px-5 rounded cursor-pointer font-semibold text-grey-900 flex w-[130px] justify-between text-sm leading-6 items-center">
                        <span>Clientes</span>
                        <svg width="10px" height="10px" viewBox="0 0 1024 1024" class="icon" version="1.1"
                            xmlns="http://www.w3.org/2000/svg">
                            <path d="M903.232 256l56.768 50.432L512 768 64 306.432 120.768 256 512 659.072z"
                                fill="#000000" />
                        </svg>

                    </div>
                    <div id="dropdown"
                        class="rounded border-grey-300 absolute top-[50px] bg-white w-[300px] shadow-md hidden">
                        <a href="{% url 'clientes:addCliente' %}"
                            class="cursor-pointer hover:bg-grey-300 p-4 block">Agregar</a>
                        <a href="{% url 'clientes:listCliente' %}"
                            class="cursor-pointer hover:bg-grey-300 p-4 block">Lista</a>
                    </div>
                </div>



                <a href="{% url 'suscripciones:listSuscripcion'%}"
                    class="text-sm font-semibold leading-6 text-gray-900">Suscripciones</a>
            </div>
            <div class="hidden lg:flex lg:flex-1 lg:justify-end">
                <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Log in <span
                        aria-hidden="true">&rarr;</span></a>
            </div>
        </nav>
        <!-- Mobile menu, show/hide based on menu open state. -->
        <div class="lg:hidden" role="dialog" aria-modal="true">
            <!-- Background backdrop, show/hide based on slide-over state. -->
            <!-- <div class="fixed inset-0 z-10"></div> -->
            <div class="fixed inset-y-0 right-0 z-10 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10"
            style="display: none;"
                id="menuContainer">
                <div class="flex items-center justify-between">
                    <a href="#" class="-m-1.5 p-1.5">
                        <span class="sr-only">Your Company</span>
                        <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
                            alt="">
                    </a>
                    <button type="button" id="closeMenuBtn" class="-m-2.5 rounded-md p-2.5 text-gray-700">
                        <span class="sr-only">Close menu</span>
                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
                            aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"></path>
                        </svg>
                    </button>
                </div>
                <div class="mt-6 flow-root">
                    <div class="-my-6 divide-y divide-gray-500/10">
                        <div class="space-y-2 py-6">
                            <a href="{% url 'servicios:listarServicios' %}"
                                class="font-semibold leading-6 text-grey-900 -mx-3 px-3 py-2">Servicios</a>

                            
                                {% include 'tools/botonCollapse.html' with title="Clientes" url1nombre="Agregar" url1="clientes:addCliente"   url2nombre="Listar" url2="clientes:listCliente"%}
                                {% include 'tools/botonCollapse.html' with title="Planes" url1nombre="Agregar" url1="planes:addPlan"   url2nombre="Listar" url2="planes:listPlan"%}
                                
                                <a href="{% url 'suscripciones:listSuscripcion' %}"
                                class="font-semibold leading-6 text-grey-900 -mx-3 px-3 py-2">Suscripciones</a>
                        </div>
                        <div class="py-6">
                            <a href="#"
                                class="-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Log
                                in</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <script>
        const closeMenuBtn = document.getElementById('closeMenuBtn');
        const menuContainer = document.getElementById('menuContainer');
        const openMenuBtn = document.getElementById('openMenuBtn')

        function cerrarMenu() {
            menuContainer.style.display = 'none';
        }

        function mostrarMenu() {
            menuContainer.style.display = 'block';
        }

        closeMenuBtn.addEventListener('click', function () {
            cerrarMenu();
        });

        openMenuBtn.addEventListener('click', function () {
            mostrarMenu();
        });
    </script>
    <script>
        function toggleDropdown(id) {
            let dropdown = document.querySelector(id)
            dropdown.classList.toggle('hidden')
        }
    </script>
    <main class="w-full px-4 py-8"> 
        {% block content %}
        {% endblock content %}
    </main>

</body>

</html>

templates/home.html
{% extends "_base.html" %}

{% block content %}

<div class="max-w-md mx-auto">
    {% for item in sus %}
        <div>
            <div>
            {{item.cliente.nombre}}

        </div>
            <div>
                {{item.fin_suscripcion_str}}
            </div>

        </div>
    {% endfor %}
</div>
{% endblock content %}