apps/clientes/urls.py
from django.urls import path, re_path
from . import views

app_name = 'clientes'

urlpatterns = [
    path('agregar/', views.agregarCliente, name="addCliente"),
    path('listar/', views.listarCliente, name="listCliente"),
    path('<int:cliente_id>/', views.detalleCliente, name="detailCliente")
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('clientes/', include('apps.clientes.urls')),   
    path('planes/', include('apps.planes.urls')),   
    path('servicios/', include('apps.servicios.urls')),   
    path('suscripciones/', include('apps.suscripciones.urls')),   
]

apps/clientes/models.py
from django.db import models

class Cliente(models.Model):
    nombre = models.CharField(max_length=240)
    dni = models.CharField(max_length=12)
    

class Contacto(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    celular = models.CharField(max_length=20)
    email = models.EmailField(max_length=100)  # Cambiado a EmailField para validar formato de correo electrónico

class Direccion(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    nombre_calle = models.CharField(max_length=100)
    numero_calle = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=100, blank=True)  # Ejemplo de campo adicional
    estado = models.CharField(max_length=100, blank=True)  # Ejemplo de campo adicional
    pais = models.CharField(max_length=100, blank=True)  # Ejemplo de campo adicional
    codigo_postal = models.CharField(max_length=20, blank=True)  # Ejemplo de campo adicional
    latitud = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    longitud = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)

    class Meta:
        indexes = [
            models.Index(fields=['latitud', 'longitud']),
            models.Index(fields=['cliente']),  # Ejemplo de índice adicional
        ]

    # Ejemplo de método para obtener la dirección completa
    def direccion_completa(self):
        return f"{self.nombre_calle} {self.numero_calle}"

apps/clientes/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from .models import Cliente, Contacto, Direccion
from apps.suscripciones.models import Suscripcion
from django.db.models import Q
# Create your views here.


def agregarCliente(request):
    if request.method == 'POST':
        print(request.POST)
        nombre = request.POST.get('nombre')
        dni = request.POST.get('dni')
        celular = request.POST.get('celular')
        email = request.POST.get('email')
        calle = request.POST.get('calle')
        numero = request.POST.get('numero_calle')
        
        clienteAdd = Cliente.objects.create(nombre=nombre,dni=dni)

        contactoAdd = Contacto.objects.create(cliente=clienteAdd, celular=celular, email=email)

        direccionAdd = Direccion.objects.create(
            cliente=clienteAdd,
            nombre_calle=calle, 
            numero_calle=numero,
            )




        print(contactoAdd.email)
        print("Nombre:", nombre)
        print("DNI:", dni)
        print("Celular:", celular)
        print("Email:", email)
        print("Calle:", calle)
        print("Número:", numero)
        print("Número:", contactoAdd)
        context = {
            'message':'Se agrego'
        }
        return render(request, 'clientes/agregarClientes.html' ,context)

    else:
        # Si la solicitud no es POST, puedes renderizar el formulario nuevamente o realizar otras acciones

        return render(request, 'clientes/agregarClientes.html')


def listarCliente(request):
    if request.method == 'POST':
        buscador = request.POST.get('buscador')
        
        listarCliente = Cliente.objects.all()

        if buscador is not None and not ' ' in buscador:
            clientes = listarCliente.filter(Q(nombre__icontains=buscador) | Q(dni__icontains=buscador))

            context = {
            'clientes':clientes
            }
            return render(request, 'clientes/listarClientes.html' ,context)
    else:

        listaClientes = Cliente.objects.all()
        context = {
            'clientes':listaClientes
        }
        return render(request, 'clientes/listarClientes.html' ,context)

def detalleCliente(request, cliente_id):
    cliente = None
    contacto_cliente = None
    direccion_cliente = None
    suscripcion_activa = None
    try:
        cliente = Cliente.objects.get(pk=cliente_id)
        contacto_cliente = Contacto.objects.get(cliente_id=cliente_id)
        direccion_cliente = Direccion.objects.get(cliente_id=cliente_id)
        suscripcion_activa = Suscripcion.objects.get(cliente_id=cliente_id)
        print(suscripcion_activa)
    except Cliente.DoesNotExist:
        # raise Http404("El cliente no existe")
        context = {
            'message':'El cliente no existe'
        }
        return render(request, 'clientes/errorCliente.html', context)
    except Contacto.DoesNotExist:
        pass  # No hay contacto asociado, contacto_cliente ya es None
    except Direccion.DoesNotExist:
        pass
    except Suscripcion.DoesNotExist:
        pass 
    
    context = {
        'cliente': cliente,
        'contacto': contacto_cliente,
        'direccion': direccion_cliente,
        'suscripcion': suscripcion_activa,

    }
    return render(request, 'clientes/detalleCliente.html', context)

templates/clientes/agregarClientes.html
{% extends "_base.html" %}

{% block content %}

<div class="flex justify-center mt-8">
    {% if message %}
    <p>SE AGREGO</p>
    {% endif %}
    <div class="w-full max-w-md">
        <form action="" method="post">
            {%csrf_token%}
            <!-- <h4 class="mb-4 text-2xl font-semibold dark:text-white">AGREGAR CLIENTE</h4> -->
            <input
                class="w-full mb-4 px-4 py-3 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500"
                type="text" placeholder="Nombre" name="nombre">
            <input
                name="dni"
                class="w-full mb-4 px-4 py-3 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500"
                type="text" placeholder="DNI" pattern="[0-9]*" title="Por favor ingrese solo números" required />

            <input
                name="celular"
                class="w-full mb-4 px-4 py-3 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500"
                type="text" placeholder="Celular">
            <input
                name="email"
                class="w-full mb-4 px-4 py-3 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500"
                type="text" placeholder="Email">
            <div class="flex">
                <input
                    name="calle"
                    class="w-3/4 mr-2 mb-4 px-4 py-3 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500"
                    type="text" placeholder="Calle">
                <input
                    name="numero_calle"
                    class="w-1/4 ml-2 mb-4 px-4 py-3 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500"
                    type="text" placeholder="Número">
            </div>

            <button
                class="w-full px-4 py-3 rounded-md bg-indigo-500 text-white font-semibold hover:bg-indigo-600 focus:outline-none focus:bg-indigo-600"
                type="submit">Agregar</button>
        </form>
        {% include 'tools/botonVolver.html '%}

    </div>
</div>



</div>


{% endblock content %}

templates/clientes/detalleCliente.html
{% extends "_base.html" %}

{% block content %}



<div class="container-detalle-cliente">
    <div class="container-datos-personales">
        <h1 style="font-weight: 600; font-size: 1.125rem;">{{cliente.nombre}}</h1>
        <div class="datos-container"> 

            <label class="label-datos">
                DNI
            </label>
            <span class="datos">
                {{cliente.dni}}
            </span>
        </div>
        <div class="datos-container"> 

            <label class="label-datos">
                Telefono
            </label>
            <span class="datos">
                {{contacto.celular}}
            </span>
        </div>
        <div class="datos-container"> 

            <label class="label-datos">
                Email:
            </label>
            <span class="datos">
                {{contacto.email}}
            </span>
        </div>
        <div class="datos-container"> 

            <label class="label-datos">
                Direccion:
            </label>
            <span class="datos">
                {{direccion.direccion_completa}}
            </span>
        </div>
    </div>
    <div style="display: flex; flex-direction: row; gap: 10px; align-items: center;">

        {% include 'clientes/enviarWsp.html' with numero=contacto.celular %}
        
        
        
        {% include 'clientes/llamarCliente.html' with numero=contacto.celular %}
    </div>


</div>
<style>
    .container-detalle-cliente {
        width: 80%;
        margin: auto;

    }

    .container-datos-personales {
        /* background-color: aqua; */
        padding: 1rem;
    }

    .datos {
        color: rgb(105, 105, 105);
        font-weight: 500;
    }

    .label-datos {
        color: rgb(105, 105, 105);

    }
    .datos-container {
        display: flex;
        flex-direction: column;
    }
</style>




<script>
    function guardarUbicacion() {
        const options = {
            enableHighAccuracy: true,
            timeout: 5000,
            maximumAge: 0,
        };

        function success(pos) {
            const crd = pos.coords;

            console.log("Tu ubicación actual es:");
            console.log(`Latitud : ${crd.latitude}`);
            console.log(`Longitud: ${crd.longitude}`);
            console.log(`Más o menos ${crd.accuracy} metros.`);

            alert(crd.longitude)
        }

        function error(err) {
            alert(`ERROR(${err.code}): ${err.message}`);
        }

        navigator.geolocation.getCurrentPosition(success, error, options);



    }


</script>


{% endblock content %}

templates/clientes/enviarWsp.html
<a href="https://wa.me/+54{{ numero }}">
    <div class="rounded-lg shadow-md w-fit w-25 bg-green-100  hover:bg-green-400">

        <button class="flex items-center space-x-2 p-2">
            <svg height="30px" width="30px" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" xml:space="preserve">
                <path style="fill:#EDEDED;"
                    d="M0,512l35.31-128C12.359,344.276,0,300.138,0,254.234C0,114.759,114.759,0,255.117,0
                        S512,114.759,512,254.234S395.476,512,255.117,512c-44.138,0-86.51-14.124-124.469-35.31L0,512z" />
                <path style="fill:#55CD6C;" d="M137.71,430.786l7.945,4.414c32.662,20.303,70.621,32.662,110.345,32.662
                        c115.641,0,211.862-96.221,211.862-213.628S371.641,44.138,255.117,44.138S44.138,137.71,44.138,254.234
                        c0,40.607,11.476,80.331,32.662,113.876l5.297,7.945l-20.303,74.152L137.71,430.786z" />
                <path style="fill:#FEFEFE;"
                    d="M187.145,135.945l-16.772-0.883c-5.297,0-10.593,1.766-14.124,5.297
                        c-7.945,7.062-21.186,20.303-24.717,37.959c-6.179,26.483,3.531,58.262,26.483,90.041s67.09,82.979,144.772,105.048
                        c24.717,7.062,44.138,2.648,60.028-7.062c12.359-7.945,20.303-20.303,22.952-33.545l2.648-12.359
                        c0.883-3.531-0.883-7.945-4.414-9.71l-55.614-25.6c-3.531-1.766-7.945-0.883-10.593,2.648l-22.069,28.248
                        c-1.766,1.766-4.414,2.648-7.062,1.766c-15.007-5.297-65.324-26.483-92.69-79.448c-0.883-2.648-0.883-5.297,0.883-7.062
                        l21.186-23.834c1.766-2.648,2.648-6.179,1.766-8.828l-25.6-57.379C193.324,138.593,190.676,135.945,187.145,135.945" />
            </svg>
            <span>Enviar Whatsapp</span>
        </button>
        
    </div>
</a>

templates/clientes/errorCliente.html
{% extends "_base.html" %}

{% block content %}


<div class="justify-center">
    {{message}}
    <a
    href="{% url 'clientes:listCliente' %}">
        <button class="px-4 py-2 bg-indigo-500 text-white font-semibold hover:bg-indigo-600 focus:outline-none focus:bg-indigo-600">Volver</button>
    </a>
        
</div>


{% endblock content %}

templates/clientes/listarClientes.html
{% extends "_base.html" %}

{% block content %}

<div class="max-w-7xl mx-auto">
    <div class="flex mb-4">
        <style>
            @media (max-width: 640px) {
                .flex-container-form {
                    width: 100%;
                }
            }
        </style>
        <form action="" method="post" class="flex items-center flex-container-form">
            {%csrf_token%}
            <input id="buscador" name="buscador"
                class="flex-1 mr-2 px-4 py-3 rounded-md border border-gray-300 placeholder-gray-500 focus:outline-none focus:border-indigo-500"
                type="text" placeholder="Buscar por nombre o DNI">
            <button type="submit"
                class="px-4 py-3 rounded-md bg-indigo-500 text-white font-semibold hover:bg-indigo-600 focus:outline-none focus:bg-indigo-600">Buscar</button>
        </form>
    </div>

    {% for cliente in clientes %}

    <style>
        .flex-container:active {
            opacity: 0.5;
        }
        .flex-container:hover {
            background-color: rgb(0,0,0,0.05);
        }
    </style>
    
    <a href="{%url 'clientes:detailCliente' cliente.id %}" style="touch-action: auto; cursor: pointer;">
        <div class="flex flex-row justify-between space-y-2 flex-container items-center p-2">
            <div class="flex flex-col">
                <span class="font-semibold text-sm">{{ cliente.nombre }}</span>
                <span class="font-semibold text-sm" style="color: rgba(99, 101, 241, 0.555)">{{ cliente.dni }}</span>
            </div>
            <div class="flex flex-col">
                <span></span>

            </div>
        </div>
    </a>
    <!-- <a href="{%url 'clientes:detailCliente' cliente.id %}" class="self-end">
        <button
        class="px-3 rounded-lg py-2 bg-indigo-500 text-white font-semibold hover:bg-indigo-600 focus:outline-none focus:bg-indigo-600">
        Ver más
    </button>
</a> -->
    {% endfor %}
</div>

{% endblock content %}

templates/clientes/llamarCliente.html
<a href="tel:+54{{ numero }}">
    <div class="rounded-lg shadow-md w-fit w-25 bg-white  hover:bg-gray-400	">

        <button class="flex items-center space-x-2 p-2">
            <svg fill="#000000" height="25px" width="25px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
            viewBox="0 0 473.806 473.806" xml:space="preserve">
       <g>
           <g>
               <path d="M374.456,293.506c-9.7-10.1-21.4-15.5-33.8-15.5c-12.3,0-24.1,5.3-34.2,15.4l-31.6,31.5c-2.6-1.4-5.2-2.7-7.7-4
                   c-3.6-1.8-7-3.5-9.9-5.3c-29.6-18.8-56.5-43.3-82.3-75c-12.5-15.8-20.9-29.1-27-42.6c8.2-7.5,15.8-15.3,23.2-22.8
                   c2.8-2.8,5.6-5.7,8.4-8.5c21-21,21-48.2,0-69.2l-27.3-27.3c-3.1-3.1-6.3-6.3-9.3-9.5c-6-6.2-12.3-12.6-18.8-18.6
                   c-9.7-9.6-21.3-14.7-33.5-14.7s-24,5.1-34,14.7c-0.1,0.1-0.1,0.1-0.2,0.2l-34,34.3c-12.8,12.8-20.1,28.4-21.7,46.5
                   c-2.4,29.2,6.2,56.4,12.8,74.2c16.2,43.7,40.4,84.2,76.5,127.6c43.8,52.3,96.5,93.6,156.7,122.7c23,10.9,53.7,23.8,88,26
                   c2.1,0.1,4.3,0.2,6.3,0.2c23.1,0,42.5-8.3,57.7-24.8c0.1-0.2,0.3-0.3,0.4-0.5c5.2-6.3,11.2-12,17.5-18.1c4.3-4.1,8.7-8.4,13-12.9
                   c9.9-10.3,15.1-22.3,15.1-34.6c0-12.4-5.3-24.3-15.4-34.3L374.456,293.506z M410.256,398.806
                   C410.156,398.806,410.156,398.906,410.256,398.806c-3.9,4.2-7.9,8-12.2,12.2c-6.5,6.2-13.1,12.7-19.3,20
                   c-10.1,10.8-22,15.9-37.6,15.9c-1.5,0-3.1,0-4.6-0.1c-29.7-1.9-57.3-13.5-78-23.4c-56.6-27.4-106.3-66.3-147.6-115.6
                   c-34.1-41.1-56.9-79.1-72-119.9c-9.3-24.9-12.7-44.3-11.2-62.6c1-11.7,5.5-21.4,13.8-29.7l34.1-34.1c4.9-4.6,10.1-7.1,15.2-7.1
                   c6.3,0,11.4,3.8,14.6,7c0.1,0.1,0.2,0.2,0.3,0.3c6.1,5.7,11.9,11.6,18,17.9c3.1,3.2,6.3,6.4,9.5,9.7l27.3,27.3
                   c10.6,10.6,10.6,20.4,0,31c-2.9,2.9-5.7,5.8-8.6,8.6c-8.4,8.6-16.4,16.6-25.1,24.4c-0.2,0.2-0.4,0.3-0.5,0.5
                   c-8.6,8.6-7,17-5.2,22.7c0.1,0.3,0.2,0.6,0.3,0.9c7.1,17.2,17.1,33.4,32.3,52.7l0.1,0.1c27.6,34,56.7,60.5,88.8,80.8
                   c4.1,2.6,8.3,4.7,12.3,6.7c3.6,1.8,7,3.5,9.9,5.3c0.4,0.2,0.8,0.5,1.2,0.7c3.4,1.7,6.6,2.5,9.9,2.5c8.3,0,13.5-5.2,15.2-6.9
                   l34.2-34.2c3.4-3.4,8.8-7.5,15.1-7.5c6.2,0,11.3,3.9,14.4,7.3c0.1,0.1,0.1,0.1,0.2,0.2l55.1,55.1
                   C420.456,377.706,420.456,388.206,410.256,398.806z"/>
               <path d="M256.056,112.706c26.2,4.4,50,16.8,69,35.8s31.3,42.8,35.8,69c1.1,6.6,6.8,11.2,13.3,11.2c0.8,0,1.5-0.1,2.3-0.2
                   c7.4-1.2,12.3-8.2,11.1-15.6c-5.4-31.7-20.4-60.6-43.3-83.5s-51.8-37.9-83.5-43.3c-7.4-1.2-14.3,3.7-15.6,11
                   S248.656,111.506,256.056,112.706z"/>
               <path d="M473.256,209.006c-8.9-52.2-33.5-99.7-71.3-137.5s-85.3-62.4-137.5-71.3c-7.3-1.3-14.2,3.7-15.5,11
                   c-1.2,7.4,3.7,14.3,11.1,15.6c46.6,7.9,89.1,30,122.9,63.7c33.8,33.8,55.8,76.3,63.7,122.9c1.1,6.6,6.8,11.2,13.3,11.2
                   c0.8,0,1.5-0.1,2.3-0.2C469.556,223.306,474.556,216.306,473.256,209.006z"/>
           </g>
       </g>
       </svg>
            <span>Llamar</span>
        </button>
        
    </div>
</a>